/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge10;

//import Challenge10.Stack.NodeStack;
import Challenge10.Stack.Stack;

import java.util.ArrayList;
import java.util.HashMap;
//import java.util.Stack;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        ValidateBracket vb = new ValidateBracket();
//        System.out.println(vb.validateBrackets(")"));
        System.out.println(vb.validateBrackets("){{}}{}"));
//        System.out.println(vb.validateBrackets("){()}"));
    }


}
