/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge15;

import Challenge15.data.Node;
import Challenge15.dataStructure.BinarySearchTree;
import Challenge15.dataStructure.BinaryTree;
import com.sun.source.tree.AssertTree;
import org.junit.Before;
import org.junit.jupiter.api.Test;


import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

@Test void getMaxTest() {
        Node root = new Node(1);
        root.setLeft(2);
        root.getLeft().setLeft(3);
        root.getLeft().setRight(4);
        root.setRight(5);
        root.getRight().setLeft(2);
        BinaryTree BT = new BinaryTree(3);
        BT.setRoot(root);
        int expected= 5;
        int actual = BT.getMax();
        assertEquals(expected,actual);
    }
    @Test void getMaxOneElementTest() {
        Node root = new Node(1);
        root.setLeft(2);
        BinaryTree BT = new BinaryTree();
        BT.setRoot(root);
        int expected= 2;
        int actual = BT.getMax();
        assertEquals(expected,actual);
    }
    @Test void nullTree() {
        Node root = new Node(1);
        root.setLeft(2);
        BinaryTree BT = new BinaryTree();
        int expected= -1;
        int actual = BT.getMax();
        assertEquals(expected,actual);
    }
}
