/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge10;


import Challenge10.Stack.NodeStack;
import Challenge10.Stack.Stack;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.NoSuchElementException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void TrueTest(){
        ValidateBracket vb = new ValidateBracket();
        assertTrue(vb.validateBrackets("{}{{}}"));
    }
    @Test void FalseTest(){
        ValidateBracket vb = new ValidateBracket();
        assertFalse(vb.validateBrackets("}{"));
    }
    @Test void OneBracketTest(){
        ValidateBracket vb = new ValidateBracket();
        assertFalse(vb.validateBrackets("}"));
    }


}
