/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge32;

import org.junit.jupiter.api.Test;


import static Challenge32.RepeatedWord.repeatedWord;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void test_NoRepeatedWord(){

    }


}
