/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge10;

import Challenge10.Queue.NodeQueue;
import Challenge10.Queue.Queue;
import Challenge10.Stack.NodeStack;
import Challenge10.Stack.Stack;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        Stack stack = new Stack();
//        stack.push(new NodeStack("Renad"));
//        stack.push(new NodeStack("Jamil"));
//        stack.push(new NodeStack("Khawatreh"));
//        stack.pop();
//        System.out.println(stack.peek());
//        System.out.println(stack);

        Queue queue = new Queue();
        queue.enqueue(new NodeQueue("Renad"));
        queue.enqueue(new NodeQueue("Jamil"));
        queue.enqueue(new NodeQueue("Mousa"));
        queue.enqueue(new NodeQueue("Khawatreh"));
        queue.dequeue();
        System.out.println(queue);
    }
}
