/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge27;

import Challenge27.dataStructure.Mergesort;
import org.junit.jupiter.api.Test;


import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void OneElementTest() {
        Mergesort mergesort = new Mergesort();
        int[] arr  ={8};
        int[] expected= {8};
        int[] actual = mergesort.MergeSort(arr);
        assertTrue(Arrays.equals(expected,actual));

    }
    @Test void TwoElement() {
        Mergesort mergesort = new Mergesort();
        int[] arr  ={8,4};
        int[] expected= {4,8};
        int[] actual = mergesort.MergeSort(arr);
        assertTrue(Arrays.equals(expected,actual));

    }
    @Test void EmptyArrayTest() {
        Mergesort mergesort = new Mergesort();
        int[] arr  ={};
        int[] expected= {};
        int[] actual = mergesort.MergeSort(arr);
        assertTrue(Arrays.equals(expected,actual));

    }
}
