/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge12;

import Challenge12.AnimalShleter.Animal;
import Challenge12.AnimalShleter.AnimalShelter;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void testAnimalShelter(){
        AnimalShelter animal = new AnimalShelter();
        Animal dog = new Animal("dog","","20/3/2022");
        animal.enqueue(dog);
        Animal dog1 = new Animal("dog","Holy","2000");
        animal.enqueue(dog1);
        Animal cat = new Animal("cat","","20/1/2022");
        animal.enqueue(cat);
        String expexted = "AnimalShelter{dogs=[type='dog', desc=''," +
                " arrivedDate='20/3/2022'}, type='dog', desc='Holy'," +
                " arrivedDate='2000'}], cats=[type='cat', desc=''," +
                " arrivedDate='20/1/2022'}]}";
        assertEquals(expexted.toString(),animal.toString());
    }
    @Test void dequeueEmptyAnimalShelter(){
        AnimalShelter animal = new AnimalShelter();
        assertNull(animal.dequeue("cat"));
    }
    @Test void enqueueAnimalBasedOnCategory(){
        AnimalShelter animal = new AnimalShelter();
        Animal dog = new Animal("dog","bulldog, age:14 ","20/3/2022");
        animal.enqueue(dog);
        Animal dog1 = new Animal("dog","black-and-tan Pomeranian","2000");
        animal.enqueue(dog1);
        Animal cat = new Animal("cat","himalayan","20/1/2022");
        animal.enqueue(cat);
        String expected = "AnimalShelter{dogs=[type='dog', desc='bulldog, age:14 ', " +
                "arrivedDate='20/3/2022'}, type='dog', desc='black-and-tan Pomeranian'," +
                " arrivedDate='2000'}], cats=[type='cat', desc='himalayan', arrivedDate='20/1/2022'}]}";
        assertEquals(expected.toString(), animal.toString());

    }

}
