/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge11;

import Challenge11.Queue.PseudoQueue;
import Challenge11.Stack.NodeStack;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.sql.PseudoColumnUsage;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void addEmptyQueue(){
        PseudoQueue queue = new PseudoQueue();
        int size =0;
        assertEquals(size,queue.getSIZE());
    }
    @Test void addMultipleElement(){
        PseudoQueue queue = new PseudoQueue();
        queue.enqueue("1");
        queue.enqueue("2");
        queue.enqueue("3");
        int size =3;
        assertEquals(size,queue.getSIZE());
    }
    @Test void DequeueEmptyQueue(){
        PseudoQueue queue = new PseudoQueue();
        String expected = "NodeStack{item='Error, The Queue is empty'}";
        assertEquals(expected.contains("Error"),queue.dequeue().toString().contains("Error") );
    }
    @Test void DequeueOnEmptyQueue(){
        PseudoQueue queue = new PseudoQueue();
        String expected = "NodeStack{item='Error, The Queue is empty'}";
        assertEquals(expected.contains("Error"),queue.dequeue().toString().contains("Error") );
    }

}
