/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge17;

import Challenge17.data.Node;
import Challenge17.dataStructure.KTree;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       Node root = new Node(2);
        Node element1 = new Node(3);
        Node element2 = new Node(4);
        Node element3 = new Node(5);
        Node element4 = new Node(6);
        Node element5 = new Node(7);
        Node element6 = new Node(15);

        root.getChildern().add(element1);
        root.getChildern().add(element2);
        root.getChildern().add(element3);
        element2.getChildern().add(element4);
        element3.getChildern().add(element5);
        element5.getChildern().add(element6);

        KTree Kt= new KTree(root);
        Kt.print(root);
        System.out.println("******************");
        Kt.fizzBuzzTree(root);
    }

}