/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge11;

import Challenge11.Queue.PseudoQueue;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        PseudoQueue queue = new PseudoQueue();
        queue.enqueue("Renad");
        queue.enqueue("Rana");
        queue.enqueue("Maryam");
        queue.enqueue("Malak");
        System.out.println(queue);
        System.out.println();
        queue.dequeue();
        System.out.println(queue);
    }
}
