/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge08;


import static Challenge08.LinkedList.zipLists;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        LinkedList<Integer> ls1 = new LinkedList<>();
//        ls1.append(1);
//        ls1.append(3);
//        ls1.append(2);
        LinkedList<Integer> ls2 = new LinkedList<>();
        ls2.append(5);
        ls2.append(9);
        ls2.append(4);
        LinkedList<Integer> res = zipLists(ls1,ls2);
        res.print();
    }
}
