/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge28;

import Challenge28.dataStructure.Quicksort;
import org.junit.jupiter.api.Test;


import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void quickSortTest() {
        String str ="";
        Quicksort quicksort = new Quicksort();
        int[] arr = { 8,4,23,24,16};
        quicksort.QuickSort(arr,0,arr.length-1);

        for (int num: arr) {
            str+=num+" => ";
        }
        assertEquals("4 => 8 => 16 => 23 => 24 => ",str);
    }
}
