/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge17;

import Challenge17.data.Node;
import Challenge17.dataStructure.BinaryTree;
import org.junit.jupiter.api.Test;


import java.util.LinkedList;
import java.util.Queue;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

@Test void getMaxTest() {
        Node root = new Node(1);
        root.setLeft(2);
        root.getLeft().setLeft(3);
        root.getLeft().setRight(4);
        root.setRight(5);
        root.getRight().setLeft(2);
        BinaryTree BT = new BinaryTree(3);
        BT.setRoot(root);
        int expected= 5;
        int actual = BT.getMax();
        assertEquals(expected,actual);
    }
    @Test void getMaxOneElementTest() {
        Node root = new Node(1);
        root.setLeft(2);
        BinaryTree BT = new BinaryTree();
        BT.setRoot(root);
        int expected= 2;
        int actual = BT.getMax();
        assertEquals(expected,actual);
    }
    @Test void nullTree() {
        Node root = new Node(1);
        root.setLeft(2);
        BinaryTree BT = new BinaryTree();
        int expected= -1;
        int actual = BT.getMax();
        assertEquals(expected,actual);
    }
    @Test void breadthFirst(){
        Node root = new Node(1);
        root.setLeft(2);
        root.getLeft().setLeft(3);
        root.getLeft().setRight(4);
        root.setRight(5);
        root.getRight().setLeft(2);
        BinaryTree BT = new BinaryTree(3);
        BT.setRoot(root);
        BT.breadthFirst(BT);
       String expected = "1 => 2 => 5 => 3 => 4 => 2 => ";
        assertEquals(expected, BT.breadthFirst(BT));

    }

}
