/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge17;

import Challenge17.data.Node;
import Challenge17.dataStructure.BinarySearchTree;
import Challenge17.dataStructure.BinaryTree;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Node root = new Node(1);
        root.setLeft(2);
        root.getLeft().setLeft(3);
        root.getLeft().setRight(4);
        root.setRight(5);
        root.getRight().setLeft(2);
        BinaryTree BT = new BinaryTree(3);
        BT.setRoot(root);
        BT.breadthFirst(BT);





//        Node root1 = new Node(3);
//        BinarySearchTree BST = new BinarySearchTree();
//        BST.setRoot(root1);
//        BST.add(1);
//        BST.add(2);
//        BST.add(4);
//        BST.add(5);
//        System.out.println(BST.Contains(root1,3));

    }

}
