/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LTUCTest;

import org.checkerframework.checker.units.qual.A;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        linkedList<Integer> ls = new linkedList<>();
        System.out.println("****************");
        ls.insert(1);
        ls.insert(2);
        ls.append(10);
        ls.insert(3);
        ls.append(12);
        ls.print();
        ls.insertAfter(2,5);
        ls.print();
        ls.insertBefore(5,9);
        ls.print();
        System.out.println(ls.kthFromEnd(2));;
        System.out.println("The length of LinkedList is: "+ls.length());
        System.out.println("****************");

    }
}
